### ISSUE TITLE
Error running webpack

### ISSUE THREAD

**Issue by ptav** [codyparker/channels-obstruction#4]
When I try to setup the project "out-of-the-box" and run node_modules/.bin/webpack I get the following error:

```C:\Users\pedro\Documents\dev\contrib\src\channels-obstruction\webpack.config.js:18
    new webpack.NoEmitOnErrorsPlugin(), // don't reload if there is an error
    ^

TypeError: webpack.NoEmitOnErrorsPlugin is not a constructor
    at Object.<anonymous> (C:\Users\pedro\Documents\dev\contrib\src\channels-obstruction\webpack.config.js:18:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\pedro\Documents\dev\contrib\src\channels-obstruction\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (C:\Users\pedro\Documents\dev\contrib\src\channels-obstruction\node_modules\webpack\bin\webpack.js:39:40)
```

I tried to resolve this by removing the offending line (18: `new webpack.NoEmitOnErrorsPlugin()`). That allows it to progress further but then fails to recognise the .jsx files. See for example:

```
Hash: c823a8b044190d0ff507
Version: webpack 1.15.0
Time: 1499ms
                        Asset    Size  Chunks             Chunk Names
 game-c823a8b044190d0ff507.js  774 kB       0  [emitted]  game
lobby-c823a8b044190d0ff507.js  774 kB       1  [emitted]  lobby
    + 183 hidden modules

ERROR in ./templates/components/lobby/index.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ./LobbyBase.jsx in C:\Users\pedro\Documents\dev\contrib\src\channels-obstruction\templates\components\lobby
resolve file
  C:\Users\pedro\Documents\dev\contrib\src\channels-obstruction\templates\components\lobby\LobbyBase.jsx.js doesn't exist
  C:\Users\pedro\Documents\dev\contrib\src\channels-obstruction\templates\components\lobby\LobbyBase.jsx.jsx doesn't exist
resolve directory
  C:\Users\pedro\Documents\dev\contrib\src\channels-obstruction\templates\components\lobby\LobbyBase.jsx\package.json doesn't exist (directory description file)
  C:\Users\pedro\Documents\dev\contrib\src\channels-obstruction\templates\components\lobby\LobbyBase.jsx is not a directory (directory default file)
[C:\Users\pedro\Documents\dev\contrib\src\channels-obstruction\templates\components\lobby\LobbyBase.jsx.js]
[C:\Users\pedro\Documents\dev\contrib\src\channels-obstruction\templates\components\lobby\LobbyBase.jsx.jsx]
 @ ./templates/components/lobby/index.jsx 7:17-43
```

The file `LobbyBase.jsx` exists in `...\templates\components\lobby`

I'm new to node so all help is appreciated

Thanks

PTav

**Comment by codyparker** [comment]
I've updated it to use webpack 3.0. Seems to work for me now.

**Comment by ptav** [comment]
Thanks codyparker, I can now run webpack. At this stage the game itself won't run but still trying to figure out why
