### ISSUE TITLE
unexpected keyword argument 'channel_layer'

### ISSUE THREAD

**Issue by Paracartoon** [codyparker/channels-obstruction#7]
Hi Cody, I hope you can help me with this issue:

`Django version 1.9, using settings 'channels_obstruction.settings'
Starting Channels development server at http://127.0.0.1:8080/
Channel layer default (asgiref.inmemory.ChannelLayer)
Quit the server with CONTROL-C.
2019-12-04 11:06:35,145 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive
2019-12-04 11:06:35,146 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive
2019-12-04 11:06:35,146 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive
2019-12-04 11:06:35,146 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fe5fbb312f0>
Traceback (most recent call last):
  File "/home/paracartoon/game/lib64/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/paracartoon/game/lib64/python3.6/site-packages/channels/management/commands/runserver.py", line 83, in inner_run
    ws_protocols=getattr(settings, 'CHANNELS_WS_PROTOCOLS', None),
TypeError: __init__() got an unexpected keyword argument 'channel_layer'
`

Seems like version conflict, however in my project Django, Channels and asgiref versions comply with yours.

**Comment by codyparker** [comment]
Hi Kate,

I haven't run this project in a while, but just cloned and tested it with Python3.6 and everything worked as expected for me. 

What does `pip freeze` show for your virtual environment?

**Comment by Paracartoon** [comment]
Thank you very much for your reply! Here is my pip freeze

`(game) bash-4.4$ pip freeze
asgiref==0.14.0
attrs==19.3.0
autobahn==19.11.1
Automat==0.8.0
cffi==1.13.2
channels==0.17.2
constantly==15.1.0
cryptography==2.8
daphne==2.4.0
Django==1.9
hyperlink==19.0.0
idna==2.8
incremental==17.5.0
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycparser==2.19
PyHamcrest==1.9.0
pyOpenSSL==19.1.0
pytz==2019.3
service-identity==18.1.0
six==1.13.0
sqlparse==0.3.0
Twisted==19.10.0
txaio==18.8.1
zope.interface==4.7.1
`

Will appreciate any suggestion =)

**Comment by codyparker** [comment]
It looks like it may be the version of daphne. You have 2.4.0, which is much newer than the version I used in this project.

Try: `pip uninstall daphne && pip install daphne==0.15.0 ` and see if that gets it working.

**Comment by Paracartoon** [comment]
Yes, it worked! Thank you!
